/**
 * Emits supabase/generated/config_seed.sql from the TypeScript balance data, so
 * the server-side economy RPCs read the same numbers the client does.
 *
 *   npm run gen:sql
 *
 * After any change under src/game/data/ (or the cost constants in
 * src/game/progression.ts), re-run this and re-paste config_seed.sql into the
 * Supabase SQL editor (after 0001 -> 0002 -> 0004). src/game/data/sql-seed.test.ts
 * fails if they drift; the CLI runs `validate()` first and aborts on any problem.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CHARACTERS } from "../src/game/data/characters";
import { RARITIES, PITY, FEATURED_5STAR_CHANCE } from "../src/game/data/gacha/rarities";
import { FOUR_STAR_FEATURED_CHANCE } from "../src/game/gacha";
import { BANNERS } from "../src/game/data/gacha/banners";
import { CHAPTER_1 } from "../src/game/data/stages/chapter-1";
import { STAGE_ORDER } from "../src/game/data/stages";
import { LEVEL_COST, STAR_UP_SHARDS, ENDLESS_MAX_WAVE } from "../src/game/progression";
import { validate } from "./validate";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "supabase", "generated", "config_seed.sql");

const str = (s: string) => `'${s.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) => `${str(JSON.stringify(v))}::jsonb`;

function valuesBlock(rows: string[]): string {
  return rows.map((r) => `  (${r})`).join(",\n") + ";";
}

export function emitConfigSql(): string {
  const characters = valuesBlock(
    CHARACTERS.map((c) => `${str(c.id)}, ${c.rarity}`),
  );

  const rarity = valuesBlock(
    (Object.keys(RARITIES) as unknown as (keyof typeof RARITIES)[]).map((r) => {
      const cfg = RARITIES[r];
      return `${r}, ${cfg.baseRate}, ${cfg.levelCap}, ${cfg.dupeShards}`;
    }),
  );

  const defaultFeaturedRate = { 5: FEATURED_5STAR_CHANCE, 4: FOUR_STAR_FEATURED_CHANCE };
  const banners = valuesBlock(
    BANNERS.map((b) => {
      const rate = { ...defaultFeaturedRate, ...(b.featuredRate ?? {}) };
      const pool = b.poolCharacters ? jsonb(b.poolCharacters) : "null";
      const starts = b.startsAt ? str(b.startsAt) : "null";
      const ends = b.endsAt ? str(b.endsAt) : "null";
      return `${str(b.id)}, ${b.costPerPull}, ${jsonb(b.featured)}, ${jsonb(rate)}, ${pool}, ${starts}, ${ends}`;
    }),
  );

  const stages = valuesBlock(
    CHAPTER_1.map((s, i) => {
      const ordinal = STAGE_ORDER.indexOf(s.id) + 1 || i + 1;
      return `${str(s.id)}, ${ordinal}, ${s.clearWithinRounds}, ${jsonb(
        s.rewards.firstClear,
      )}, ${jsonb(s.rewards.repeat)}`;
    }),
  );

  const starUp = valuesBlock([
    ...Object.entries(STAR_UP_SHARDS).map(([star, shards]) => `'*', ${star}, ${shards}`),
    ...CHARACTERS.flatMap((c) =>
      Object.entries(c.starUp ?? {}).map(([star, shards]) => `${str(c.id)}, ${star}, ${shards}`),
    ),
  ]);

  const constants = valuesBlock(
    [
      ["hard5star", PITY.hard5star],
      ["soft5star_start", PITY.soft5starStart],
      ["guaranteed4star", PITY.guaranteed4star],
      ["featured5_chance", FEATURED_5STAR_CHANCE],
      ["featured4_chance", FOUR_STAR_FEATURED_CHANCE],
      ["level_cost_gold_base", LEVEL_COST.goldBase],
      ["level_cost_gold_per", LEVEL_COST.goldPerLevel],
      ["level_cost_xp_divisor", LEVEL_COST.xpItemsDivisor],
      ["endless_max_wave", ENDLESS_MAX_WAVE],
    ].map(([k, v]) => `${str(String(k))}, ${v}`),
  );

  return `-- GENERATED by scripts/gen-sql-config.ts — do not edit. Run \`npm run gen:sql\`.
-- Paste into the Supabase SQL editor after 0001_init.sql, 0002_server_authoritative.sql, 0004_banner_pipeline.sql.
begin;

truncate app.characters, app.rarity_config, app.banners, app.stages,
  app.star_up_cost, app.game_constants;

insert into app.characters (character_key, rarity) values
${characters}

insert into app.rarity_config (rarity, base_rate, level_cap, dupe_shards) values
${rarity}

insert into app.banners (banner_id, cost_per_pull, featured, featured_rate, pool_characters, starts_at, ends_at) values
${banners}

insert into app.stages (stage_id, ordinal, clear_within_rounds, first_clear, repeat) values
${stages}

insert into app.star_up_cost (character_key, target_star, shards) values
${starUp}

insert into app.game_constants (key, value) values
${constants}

commit;
`;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const errs = validate();
  if (errs.length > 0) {
    console.error(`game data invalid — fix these before generating SQL:`);
    for (const e of errs) console.error(`  - ${e}`);
    process.exit(1);
  }
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, emitConfigSql());
  console.log(`Wrote ${OUT}`);
}
